namespace CRS.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class WarehouseAdd : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Warehouses",
                c => new
                    {
                        WarehouseId = c.Int(nullable: false, identity: true),
                        PerviousCGPA = c.Double(nullable: false),
                        NextCGPA = c.Double(nullable: false),
                        BusinessMath1 = c.Boolean(),
                        BasicsInNaturalScience = c.Boolean(),
                        EnglishReadingSkillsAndPublicSpeaking = c.Boolean(),
                        BusinessMath2 = c.Boolean(),
                        EnglishWritingSkillsAndCommunication = c.Boolean(),
                        PrinciplesOfAccounting = c.Boolean(),
                        PrinciplesOfManagement = c.Boolean(),
                        ManagementInformationSystem = c.Boolean(),
                        BusinessCommunications = c.Boolean(),
                        PrinciplesOfEconomics = c.Boolean(),
                        PrinciplesOfMarketing = c.Boolean(),
                        BusinessStatistics = c.Boolean(),
                        ComputerUtilizationInBusiness = c.Boolean(),
                        DecisionSupportSystem = c.Boolean(),
                        GlobalInformationTechnologyManagement = c.Boolean(),
                        DifferentialCalculusAndCoordinateGeometry = c.Boolean(),
                        Physics1 = c.Boolean(),
                        Physics1Lab = c.Boolean(),
                        IntegralCalculusAndOrdinaryDifferentialEquation = c.Boolean(),
                        Physics2 = c.Boolean(),
                        Physics2Lab = c.Boolean(),
                        ComplexVariableLaplaceAndZTransformation = c.Boolean(),
                        ElectricalCircuits1 = c.Boolean(),
                        ElectricalCircuits1Lab = c.Boolean(),
                        ElectricalCircuits2 = c.Boolean(),
                        ElectricalCircuits2Lab = c.Boolean(),
                        ElectronicDevicesLab = c.Boolean(),
                        ElectronicDevices = c.Boolean(),
                        ComputerAidedDesignAndDrafting = c.Boolean(),
                        MatricesVectorsFourierAnalysis = c.Boolean(),
                        DigitalLogicDesign = c.Boolean(),
                        DigitalLogicDesignLab = c.Boolean(),
                        MathematicalMethodsOfEngineering = c.Boolean(),
                        StatisticsAndProbability = c.Boolean(),
                        DigitalElectronics = c.Boolean(),
                        DigitalElectronicsLab = c.Boolean(),
                        EngineeringManagement = c.Boolean(),
                        ElectronicsShop = c.Boolean(),
                        MicroprocessorAndIOSystem = c.Boolean(),
                        EngineeringEthics = c.Boolean(),
                        DigitalSignalProcessing = c.Boolean(),
                        NetworkResourceManagement = c.Boolean(),
                        VHDLModelingAndLogicSynthesis = c.Boolean(),
                        VLSICircuitDesign = c.Boolean(),
                        SignalsAndLinearSystem = c.Boolean(),
                        RoboticsEngineering = c.Boolean(),
                        LinearAlgebraComplexVariableLaplaceTransformationAndFourierAnalysis = c.Boolean(),
                        IntroductionToElectricalEngineering = c.Boolean(),
                        IntroductionToElectricalEngineeringLab = c.Boolean(),
                        ProgrammingLanguage1 = c.Boolean(),
                        ComputerFundamentals = c.Boolean(),
                        DiscreteMathematics = c.Boolean(),
                        ProgrammingLanguage2 = c.Boolean(),
                        DataStructure = c.Boolean(),
                        IntroductionToDatabase = c.Boolean(),
                        ComputerOrganizationAndArchitecture = c.Boolean(),
                        Algorithms = c.Boolean(),
                        ObjectOrientedProgramming1 = c.Boolean(),
                        OperatingSystems = c.Boolean(),
                        ObjectOrientedAnalysisAndDesign = c.Boolean(),
                        ObjectOrientedProgramming2 = c.Boolean(),
                        SoftwareEngineering = c.Boolean(),
                        ComputerNetworks = c.Boolean(),
                        TheoryOfComputation = c.Boolean(),
                        CompilerDesign = c.Boolean(),
                        CSMath = c.Boolean(),
                        WebTechnologies = c.Boolean(),
                        AdvancedComputerNetworks = c.Boolean(),
                        ArtificialIntelligenceAndExpertSystems = c.Boolean(),
                        ResearchMethodology = c.Boolean(),
                        Thesis = c.Boolean(),
                        Internship = c.Boolean(),
                        AdvanceDatabaseManagementSystem = c.Boolean(),
                        BasicGraphTheory = c.Boolean(),
                        MultimediaSystems = c.Boolean(),
                        DataWarehousingAndDataMining = c.Boolean(),
                        SoftwareDevelopmentProjectManagement = c.Boolean(),
                        FormalMethodsofSoftwareEngineering = c.Boolean(),
                        HumanComputerInteraction = c.Boolean(),
                        SoftwareRequirementsEngineering = c.Boolean(),
                        EmbeddedTechnologies = c.Boolean(),
                        AdvancedTopicsInProgramming1 = c.Boolean(),
                        AdvancedTopicsInProgramming2 = c.Boolean(),
                        AdvancedTopicsInProgramming3 = c.Boolean(),
                        ComputerVisionAndPatternRecognition = c.Boolean(),
                        LinearProgramming = c.Boolean(),
                        NetworkSecurity = c.Boolean(),
                        EmbeddedSystemSoftware = c.Boolean(),
                        SoftwareQualityAndTesting = c.Boolean(),
                        AdvancedOperatingSystem = c.Boolean(),
                        ComputerGraphics = c.Boolean(),
                        SimulationAndModelling = c.Boolean(),
                        EGovernance = c.Boolean(),
                        EnterpriseResourcePlanning = c.Boolean(),
                        ComputerAndInformationEthics = c.Boolean(),
                        SoftwareProject1 = c.Boolean(),
                        SoftwareProject2 = c.Boolean(),
                        InternetSecurity = c.Boolean(),
                    })
                .PrimaryKey(t => t.WarehouseId);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.Warehouses");
        }
    }
}
