// <auto-generated />
namespace CRS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PrerequisiteStructureChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrerequisiteStructureChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201807281813417_PrerequisiteStructureChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
